yamlname: Build Unsigned iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Сборка архива без строгой проверки подписи
      - name: Build archive
        run: |
          xcodebuild -workspace FreeFcc.xcworkspace \
                     -scheme FreeFCC \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $RUNNER_TEMP/FreeFCC.xcarchive archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

      # Экспорт в .ipa файл
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath $RUNNER_TEMP/FreeFCC.xcarchive \
                     -exportPath build/ipa \
                     -exportOptionsPlist ExportOptions.plist \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

      # Сохранение готового файла
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-app-ipa
          path: build/ipa/*.ipa

