yamlname: Build Unsigned FreeFCC IPA

on:
  push:
    branches: [ main ] # Сборка запускается при пуше в ветку main

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Сборка архива приложения FreeFCC без подписи
      - name: Build archive
        run: |
          xcodebuild -project FreeFCC.xcodeproj \
                     -scheme FreeFCC \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $RUNNER_TEMP/FreeFCC.xcarchive archive \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

      # Экспорт архива в готовый файл .ipa
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath $RUNNER_TEMP/FreeFCC.xcarchive \
                     -exportPath build/ipa \
                     -exportOptionsPlist ExportOptions.plist \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

      # Сохранение готового .ipa файла в артефакты GitHub
      - name: Upload FreeFCC IPA
        uses: actions/upload-artifact@v4
        with:
          name: FreeFCC-unsigned-ipa
          path: build/ipa/*.ipa

